export type BadgeType =
  | 'purple'
  | 'fuchsia'
  | 'violet'
  | 'indigo'
  | 'blue'
  | 'sky'
  | 'cyan'
  | 'teal'
  | 'emerald'
  | 'green'
  | 'rose'
  | 'lime'
  | 'orange'
  | 'yellow'
  | 'amber'
  | 'red'
  | 'primary'
  | 'dark'
  | 'pink'

export type BadgeSize = 'xs' | 'sm'

export type BadgeVariant = 'default' | 'counter' | 'indicator'
