<template>
  <div class="max-w-lg w-full bg-white rounded-lg shadow dark:bg-gray-800 p-4 md:p-6">
    <div class="flex justify-between mb-3">
      <div class="flex justify-center items-center">
        <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white pe-1">
          Report Status
        </h5>
        <svg
          data-popover-target="chart-info"
          data-popover-placement="bottom"
          class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path
            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"
          />
        </svg>
        <div
          data-popover
          id="chart-info"
          role="tooltip"
          class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
        >
          <div class="p-3 space-y-2">
            <h3 class="font-semibold text-gray-900 dark:text-white">
              Activity growth - Incremental
            </h3>
            <p>
              Report helps navigate cumulative growth of community activities. Ideally, the chart
              should have a growing trend, as stagnating chart signifies a significant decrease of
              community activity.
            </p>
            <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
            <p>
              For each date bucket, the all-time volume of activities is calculated. This means that
              activities in period n contain all activities up to period n, plus the activities
              generated by your community in period.
            </p>
            <a
              href="#"
              class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline"
              >Read more
              <svg
                class="w-2 h-2 ms-1.5 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 6 10"
              >
                <path
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="m1 9 4-4-4-4"
                /></svg
            ></a>
          </div>
          <div data-popper-arrow></div>
        </div>
      </div>
      <div>
        <FwbTooltip placement="bottom" trigger="hover">
          <template #trigger>
            <FwbButton color="secondary" class="border-0" square>
              <svg
                class="w-3.5 h-3.5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 16 18"
              >
                <path
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 1v11m0 0 4-4m-4 4L4 8m11 4v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-3"
                />
              </svg>
            </FwbButton>
          </template>
          <template #content> Download CSV </template>
        </FwbTooltip>
      </div>
    </div>

    <div>
      <div class="flex" id="devices">
        <div class="flex items-center gap-4 w-full">
          <FwbCheckbox
            label="Ticket"
            @change="handleCheckboxChange()"
            v-model="checks.ticket.value"
          />
          <FwbCheckbox
            label="Issue"
            @change="handleCheckboxChange()"
            v-model="checks.issues.value"
          />
        </div>
      </div>
    </div>

    <!-- Donut Chart -->
    <div class="py-6" id="donut-chart" ref="chartContainer"></div>

    <div
      class="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between"
    >
      <div class="flex justify-between items-center pt-5">
        <TimeRangeDropdown :selected-range="selectedRange" @range-changed="handleRangeChange" />
        <FwbButton color="terciary" class="whitespace-nowrap" @click="generateReport">
          Report Analysis
          <template #suffix>
            <svg
              class="w-2.5 h-2.5 ms-1.5 rtl:rotate-180"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 6 10"
            >
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="m1 9 4-4-4-4"
              />
            </svg>
          </template>
        </FwbButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, computed, watch, reactive } from 'vue'
import { useChartOptions } from './composables/useChartOptions'
import ApexCharts from 'apexcharts'
import { initFlowbite } from 'flowbite'
import TimeRangeDropdown from './TimeRangeDropdown.vue'
import FwbButton from '@/components/FwbButton/FwbButton.vue'
import FwbCheckbox from '@/components/FwbCheckbox/FwbCheckbox.vue'
import FwbTooltip from '@/components/FwbTooltip/FwbTooltip.vue'

const props = defineProps({
  initialData: {
    type: Object,
    required: true
  }
})

const emit = defineEmits(['fetch-data', 'generate-report'])

const chartData = ref(props.initialData)
const selectedRange = ref('Last 7 days')
const chartContainer = ref(null)
let chartInstance = null

const checks = reactive({
  issues: {
    value: true,
    series: [20, 10, 56, 40]
  },
  ticket: {
    value: true,
    series: [25, 26, 14, 34]
  }
})

const renderChart = () => {
  if (chartInstance) {
    chartInstance.destroy()
  }

  const { options } = useChartOptions()
  options.labels = chartData.value.labels
  options.series = chartData.value.series

  if (chartContainer.value) {
    chartInstance = new ApexCharts(chartContainer.value, options)
    chartInstance.render()
  }
}

const handleCheckboxChange = () => {
  let newSeries
  if (checks.issues.value && checks.ticket.value) {
    newSeries = [45, 36, 70, 74]
  } else if (checks.issues.value && !checks.ticket.value) {
    newSeries = checks.issues.series
  } else if (!checks.issues.value && checks.ticket.value) {
    newSeries = checks.ticket.series
  } else {
    checks.issues.value = true
    checks.ticket.value = true
    newSeries = [45, 36, 70, 74]
  }

  if (chartInstance) {
    chartInstance.updateSeries(newSeries)
  }
}

const handleRangeChange = async (newRange) => {
  selectedRange.value = newRange
  const newData = await emit('fetch-data', newRange)
  if (newData) {
    chartData.value = newData
    renderChart()
  }
}

const generateReport = () => {
  emit('generate-report', selectedRange.value)
}

watch(
  () => props.initialData,
  (newData) => {
    chartData.value = newData
    renderChart()
  },
  { deep: true }
)

onMounted(() => {
  initFlowbite()
  renderChart()
})

onBeforeUnmount(() => {
  if (chartInstance) {
    chartInstance.destroy()
  }
})
</script>
