<template>
  <div class="max-w-lg w-full bg-white rounded-lg shadow dark:bg-neutral-800 p-4 md:p-6">
    <div class="flex justify-between mb-3">
      <div class="flex items-center">
        <div class="flex justify-center items-center">
          <h5 class="text-xl font-bold leading-none text-neutral-900 dark:text-white pe-1">
            Income Goals
          </h5>
          <svg
            data-popover-target="chart-info"
            data-popover-placement="bottom"
            class="w-3.5 h-3.5 text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white cursor-pointer ms-1"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"
            />
          </svg>
          <div
            data-popover
            id="chart-info"
            role="tooltip"
            class="absolute z-10 invisible inline-block text-sm text-neutral-500 transition-opacity duration-300 bg-white border border-neutral-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-neutral-800 dark:border-neutral-600 dark:text-neutral-400"
          >
            <div class="p-3 space-y-2">
              <h3 class="font-semibold text-neutral-900 dark:text-white">
                Activity growth - Incremental
              </h3>
              <p>
                Report helps navigate cumulative growth of community activities. Ideally, the chart
                should have a growing trend, as stagnating chart signifies a significant decrease of
                community activity.
              </p>
              <h3 class="font-semibold text-neutral-900 dark:text-white">Calculation</h3>
              <p>
                For each date bucket, the all-time volume of activities is calculated. This means
                that activities in period n contain all activities up to period n, plus the
                activities generated by your community in period.
              </p>
              <a
                href="#"
                class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline"
                >Read more
                <svg
                  class="w-2 h-2 ms-1.5 rtl:rotate-180"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 6 10"
                >
                  <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="m1 9 4-4-4-4"
                  /></svg
              ></a>
            </div>
            <div data-popper-arrow></div>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-neutral-50 dark:bg-neutral-700 p-3 rounded-lg">
      <div class="grid grid-cols-3 gap-3 mb-2">
        <dl
          class="bg-blue-50 dark:bg-neutral-600 rounded-lg flex flex-col items-center justify-center h-[78px]"
        >
          <dt
            class="w-8 h-8 rounded-full bg-blue-100 dark:bg-neutral-500 text-blue-600 dark:text-blue-300 text-sm font-medium flex items-center justify-center mb-1"
          >
            12
          </dt>
          <dd class="text-blue-600 dark:text-blue-300 text-sm font-medium">By days</dd>
        </dl>
        <dl
          class="bg-emerald-50 dark:bg-neutral-600 rounded-lg flex flex-col items-center justify-center h-[78px]"
        >
          <dt
            class="w-8 h-8 rounded-full bg-emerald-100 dark:bg-neutral-500 text-emerald-600 dark:text-emerald-300 text-sm font-medium flex items-center justify-center mb-1"
          >
            23
          </dt>
          <dd class="text-emerald-600 dark:text-emerald-300 text-sm font-medium">By trucks</dd>
        </dl>
        <dl
          class="bg-amber-50 dark:bg-neutral-600 rounded-lg flex flex-col items-center justify-center h-[78px]"
        >
          <dt
            class="w-8 h-8 rounded-full bg-amber-100 dark:bg-neutral-500 text-amber-600 dark:text-amber-300 text-sm font-medium flex items-center justify-center mb-1"
          >
            64
          </dt>
          <dd class="text-amber-600 dark:text-amber-300 text-sm font-medium">By customers</dd>
        </dl>
      </div>
      <button
        data-collapse-toggle="more-details"
        type="button"
        class="hover:underline text-xs text-neutral-500 dark:text-neutral-400 font-medium inline-flex items-center"
      >
        Show more details
        <svg
          class="w-2 h-2 ms-1"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 10 6"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="m1 1 4 4 4-4"
          />
        </svg>
      </button>
      <div
        id="more-details"
        class="border-neutral-200 border-t dark:border-neutral-600 pt-3 mt-3 space-y-2 hidden"
      >
        <dl class="flex items-center justify-between">
          <dt class="text-neutral-500 dark:text-neutral-400 text-sm font-normal">
            Average goal completion rate:
          </dt>
          <dd
            class="bg-green-100 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-green-900 dark:text-green-300"
          >
            <svg
              class="w-2.5 h-2.5 me-1.5"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 10 14"
            >
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 13V1m0 0L1 5m4-4 4 4"
              />
            </svg>
            57%
          </dd>
        </dl>
        <dl class="flex items-center justify-between">
          <dt class="text-neutral-500 dark:text-neutral-400 text-sm font-normal">
            Date until ends:
          </dt>
          <dd
            class="bg-neutral-100 text-neutral-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-neutral-600 dark:text-neutral-300"
          >
            13 days
          </dd>
        </dl>
      </div>
    </div>

    <!-- Radial Chart -->
    <div class="py-6" id="radial-chart" ref="chartContainer"></div>

    <div
      class="grid grid-cols-1 items-center border-neutral-200 border-t dark:border-neutral-700 justify-between"
    >
      <div class="flex justify-between items-center pt-5">
        <!-- Button -->
        <TimeRangeDropdown />
        <FwbButton color="terciary" class="whitespace-nowrap">
          Incomes Goals Report
          <template #suffix>
            <svg
              class="w-2.5 h-2.5 ms-1.5 rtl:rotate-180"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 6 10"
            >
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="m1 9 4-4-4-4"
              />
            </svg>
          </template>
        </FwbButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue'
import { useChartData } from './composables/useChartData'
import { useChartOptions } from './composables/useChartOptions'
import { initFlowbite } from 'flowbite'
import ApexCharts from 'apexcharts'
import TimeRangeDropdown from './TimeRangeDropdown.vue'
import FwbButton from '@/components/FwbButton/FwbButton.vue'

const chartContainer = ref(null)
let chartInstance = null

const renderChart = () => {
  if (chartInstance) {
    chartInstance.destroy()
  }

  const { options } = useChartOptions()
  const { chartData } = useChartData()

  // Desactivar animación inicial
  options.chart = {
    ...options.chart
  }
  options.series = chartData.series

  if (chartContainer.value) {
    chartInstance = new ApexCharts(chartContainer.value, options)
    chartInstance.render()
  }
}

onMounted(() => {
  initFlowbite()
  renderChart()
})

onBeforeUnmount(() => {
  if (chartInstance) {
    chartInstance.destroy()
  }
})
</script>

<style scoped></style>
